### ISSUE TITLE
cmake flexi

### ISSUE THREAD

**Issue by franalcantara** [flexi-framework/relexi#1]
Hello, I am trying to configure the make file for FLEXI following the documentation. When executing the line

`(env_relexi) francisco@francisco:~/relexi/flexi-extensions/build$ cmake .. -DLIBS_BUILD_HDF5=ON -DLIBS_USE_MPI=OFF -DLIBS_USE_SMARTREDIS=ON -DLIBS_USE_FFTW=ON -DPOSTI=OFF -DFLEXI_TESTCASE=hit -DFLEXI_NODETYPE=GAUSS-LOBATTO -DFLEXI_SPLIT_DG=ON -DFLEXI_EDDYVISCOSITY=ON`

I am getting the following error:

`[  7%] Built target userblocklib
fatal: no es posible acceder a 'https://gitlabext.iag.uni-stuttgart.de/libs/FFTW.git/': SSL: certificate subject name (gitlab.iag.uni-stuttgart.de) does not match target host name 'gitlabext.iag.uni-stuttgart.de'
Clonando en 'fftw'...
fatal: no es posible acceder a 'https://gitlabext.iag.uni-stuttgart.de/libs/FFTW.git/': SSL: certificate subject name (gitlab.iag.uni-stuttgart.de) does not match target host name 'gitlabext.iag.uni-stuttgart.de'
Clonando en 'fftw'...
fatal: no es posible acceder a 'https://gitlabext.iag.uni-stuttgart.de/libs/FFTW.git/': SSL: certificate subject name (gitlab.iag.uni-stuttgart.de) does not match target host name 'gitlabext.iag.uni-stuttgart.de'
-- Had to git clone more than once: 3 times.
CMake Error at /home/francisco/relexi/flexi-extensions/share/GNU/fftw/tmp/fftw-gitclone.cmake:39 (message):
  Failed to clone repository:
  'https://gitlabext.iag.uni-stuttgart.de/libs/FFTW.git'

make[2]: *** [CMakeFiles/fftw.dir/build.make:98: /home/francisco/relexi/flexi-extensions/share/GNU/fftw/src/fftw-stamp/fftw-download] Error 1
make[1]: *** [CMakeFiles/Makefile2:166: CMakeFiles/fftw.dir/all] Error 2
make[1]: *** Se espera a que terminen otras tareas....`

The configuration continues with more errors of unrecognized variables and reaches the [10%] with this error:

`[ 10%] Completed 'HDF5'
[ 10%] Built target HDF5
make: *** [Makefile:146: all] Error 2`

**Comment by m-kurz** [comment]
Hi, thanks for the feedback.
That's actually an error from our side and also bad timing I guess. FLEXI can install its own dependencies by itself and gets the necessary sources from a Gitlab server that's hosted by us. We just moved it to a new URL a few days back and the forwarding from the old to the new URL seems to have some issues due to the SSL certificates. I've now changed the paths to the correct ones.
Performing a "git pull" or cloning again should resolve this issue.
Can you give me confirmation whether it works?

**Comment by franalcantara** [comment]
I confirm that the problem is solved now. I close the issue
